### ISSUE TITLE
Does not bot the game?

### ISSUE THREAD

**Issue by Sqet7** [brandonabela/8-Ball-Pool-Bot#18]
Hi i have constructed this program with all the correctly. The application opens, i login fine but when i click play game nothing happens apart from getting a message box saying either "Game is not in menu but still successful login" or "Game is in main menu with successful login"

**Comment by brandonabela** [comment]
Hi,

Thank you for taking the time to create an issue. The play game logic has not been implemented yet since the testing carried out so far was done on a recorded video. 

Thank you.
