### ISSUE TITLE
hello bro 

### ISSUE THREAD

**Issue by kill699er** [brandonabela/8-Ball-Pool-Bot#19]
sorry bro couldn't find a way to contact u, ,if u have email or something so i can contact u , i just want to ask what do i need to learn so i can continue this project im quite interested in it, thanks in advance:)

**Comment by KeithGeorgeCiantar** [comment]
Hello,

Currently the project makes use of the standard Python library OpenCV, to carry out image processing on the captured frames. This library helps to detect the balls and edges, and also improves the classification between solids and stripes. Furthermore, the libraries PyAutoGUI and Selenium are also used. These detect the components inside the flash game, as well as the elements in the website itself, and can interact with them as necessary. In addition to these, basic knowledge of mathematical concepts like lines and vectors would be quite helpful, as these are a common part of the program's logic. Lastly, a good overall grasp of Python is quite important, as certain tricks can be very helpful to shorten and improve the readability of the code.
